{{- range $dbType, $dbDetail := $.Values }}
{{- if and (kindIs "map" $dbDetail) (hasKey $dbDetail "enabled") ($dbDetail.enabled) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubernetes-database-backup.fullname" $ }}-{{ $dbType }}-storage
  labels:
    {{- include "kubernetes-database-backup.labels" $ | nindent 4 }}
    database-type: {{ $dbType }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ $.Values.persistence.size }}
{{- end }}
{{- end }}