fullnameOverride: ""

s3:
  endpoint: ""
  accessKey: ""
  secretKey: ""

mongodb:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []
  # instances:
  #   - hostname: mongodb-1
  #     namespace: namespace-1
  #     port: 27017

postgresql:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []
  # instances:
  #   - name: postgresql-1
  #     namespace: ns-1

mysql:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

mariadb:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

milvus:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

# Persistence configuration
persistence:
  storageClass: ""
  size: ""

# Service Account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# RBAC configuration
rbac:
  create: true
  clusterRole: true

# Image configuration
image:
  repository: "ghcr.io/debjotimallick/kubernetes-database-backup"
  tag: "latest"
  pullPolicy: IfNotPresent
  pullSecrets: []

# Job configuration
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 1
