fullnameOverride: ""

s3:
  endpoint: ""
  accessKey: ""
  secretKey: ""

mongodb:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

postgresql:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

mysql:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

mariadb:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

milvus:
  enabled: false
  schedule: ""
  bucketName: ""
  bucketRegion: ""
  instances: []

# Persistence configuration
persistence:
  storageClass: ""
  size: ""

# Service Account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# RBAC configuration
rbac:
  create: true
  clusterRole: true

# Image configuration
image:
  repository: "ghcr.io/debjotimallick/kubernetes-database-backup"
  tag: "latest"
  pullPolicy: IfNotPresent

# Job configuration
concurrencyPolicy: Forbid
successfulJobsHistoryLimit: 3
failedJobsHistoryLimit: 1
